# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

############################### Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Enjoy Agile
#email: -
description: > 
  Communauté sur Slack reliée autour des sujets de l'agilité, scrum, kanban, management 3.0, les environnements avec membres d'équipes engagés.
url: "https://alexthib.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

############################### Handling Reading
encoding: UTF-8

############################### Serving
baseurl: "" # does not include hostname (i.e. /blog)
show_dir_listing: false

############################### Outputting
permalink: /:categories/:title/
timezone: Europe/Paris
excerpt_separator: <!--more-->
paginate: 5
paginate_path: /page:num/

############################### Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
