# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

############################### Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Enjoy Agile
email: alexthib@yahoo.com
description: > 
  Enjoy Agile est un blog sur l'agilité, le scrum, le kanban, le bonheur au travail, le management 3.0 et la création d'environnements de travail où les membres d'équipes sont engagés.
url: "http://enjoyagile.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AlexandreThib
#github_username:  alexthib

############################### Handling Reading
encoding: UTF-8

############################### Serving
#detach:  false
#port:    4000
#host:    127.0.0.1
baseurl: "" # does not include hostname (i.e. /blog)
show_dir_listing: false

############################### Outputting
permalink: /:categories/:title/
paginate: 3
paginate_path: /page:num
timezone: Europe/Paris

############################### Build settings
markdown: kramdown
#theme: jekyll-theme-minimal
gems:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
